#!/usr/local/bin/ruby
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, '..', 'lib')

require 'ruby_language_server'

application = RubyLanguageServer::Application.new
application.start
